### ISSUE TITLE
Adding builders of the same "type"

### ISSUE THREAD

**Issue by willdurand** [cedriclombardot/TwigGenerator#16]
Hi!

In `Generator::addBuilder()`, [this line](https://github.com/cedriclombardot/TwigGenerator/blob/master/src/TwigGenerator/Builder/Generator.php#L133) adds a builder by using its "simple name" as key:

     $this->builders[$builder->getSimpleClassName()] = $builder;

This makes builders not reusable, and I don't see the point here.

For instance, I have a builder for "Model" classes, each has a unique class name, but the body of all classes is pretty much the same. So I have only one builder and and I pass the class name as constructor's parameter. However, I can't easily add my builders to the `Generator` because of the line mentioned above. I had to override the `getSimpleClassName()` method, but it is a bit annoying.

WDYT? Any reason to use `getSimpleClassName()` as key here?

**Comment by cedriclombardot** [comment]
I think we could change this line by :

````
 $this->builders[] = $builder;
````

Can you test it ? For me the unique key is never used to get a builder but was only added to be sure you not do twice add with same builder

**Comment by willdurand** [comment]
Looks like this works for me..

**Comment by cedriclombardot** [comment]
Merged in #17
